# ngs360-omics-run-event-processor

AWSTemplateFormatVersion: '2010-09-09'
Description: NGS360 Omics Run/Batch Event Processor CloudFormation Template

Parameters:
  DeadLetterEmail:
    Type: String
    Description: Email address to send notifications for failed Lambda executions
  Ngs360ApiServer:
    Type: String
    Description: NGS360 REST API Server URL
  ApiServer:
    Type: String
    Description: GA4GH WES API Server URL
  ApiServerAuthToken:
    Type: String
    NoEcho: true
    Description: Authentication token for GA4GH WES API Server
  DataLakeBucket:
    Type: String
    Description: S3 Bucket name for storing omics run event data
  BucketPrefix:
    Type: String
    Default: omics-run-events
    Description: S3 Prefix (folder) within the Data Lake Bucket to store omics run event data
  VerboseLogging:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Enable verbose logging in the Lambda function
  SecurityGroupId:
      Type: String
      Description: Security Group ID for the Lambda function
  SubnetId:
      Type: String
      Description: Subnet ID for the Lambda function
  OmicsRoleArn:
      Type: String
      Description: ARN of the IAM role for AWS Omics workflow execution

Resources:
  ApiServerAuthTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: NGS360 GA4GH WES API Server credentials
      SecretString: !Sub |
        {
          "AUTH_TOKEN": "${ApiServerAuthToken}"
        }

  DeadLetterQueue:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: ngs360-lambda-event-processor-dead-letter-queue
      Subscription:
        - Endpoint: !Ref DeadLetterEmail
          Protocol: email

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref DeadLetterQueue
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${DataLakeBucket}/*
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource:
                  - !Ref ApiServerAuthTokenSecret
        - PolicyName: OmicsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - omics:GetRun
                  - omics:ListRuns
                  - omics:ListRunTasks
                  - omics:StartRun
                  - omics:TagResource
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !Ref OmicsRoleArn
        - PolicyName: BatchAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - batch:DescribeJobs
                  - batch:ListJobs
                Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        S3Bucket: !Ref DataLakeBucket
        S3Key: !Join ['', [!Ref BucketPrefix, '/lambda-package.zip']]

      DeadLetterConfig:
        TargetArn: !Ref DeadLetterQueue
      Description: NGS360 Omics Run/Batch Event Processor Lambda Function
      Environment:
        Variables:
          NGS360_API_SERVER: !Ref Ngs360ApiServer
          API_SERVER: !Ref ApiServer
          DATA_LAKE_BUCKET: !Ref DataLakeBucket
          S3_PREFIX: !Ref BucketPrefix
          VERBOSE_LOGGING: !Ref VerboseLogging
          ENV_SECRETS: !Ref ApiServerAuthTokenSecret
          OMICS_ROLE_ARN: !Ref OmicsRoleArn

      Handler: lambda.lambda_handler
      LoggingConfig: 
        LogFormat: Text
        LogGroup: /aws/lambda/ngs360/omics-run-event-processor

      PackageType: Zip

      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
  
      Tags: 
        - Key: Application
          Value: NGS360
        - Key: Service
          Value: OmicsRunEventProcessor
      Timeout: 900
      VpcConfig: 
        SecurityGroupIds: 
          - !Ref SecurityGroupId
        SubnetIds: 
          - !Ref SubnetId

  OmicsRunEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: EventBridge Rule to trigger Omics Run Event Processor Lambda Function
      EventPattern:
        source:
          - aws.omics
        detail-type:
          - Run Status Change
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: LambdaFunctionTarget

  BatchEventRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: EventBridge Rule to trigger Lambda Function on AWS Batch Job State Change events
      EventPattern:
        source:
          - aws.batch
        detail-type:
          - Batch Job State Change
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: LambdaFunctionTarget

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com

Outputs:
  LambdaFunctionName:
    Description: Name of the Omics Run Event Processor Lambda Function
    Value: !Ref LambdaFunction
